//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.16 at 09:30:59 AM KST 
//


package kr.go.mpss.idsl.dmr.ip.link.esaram;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dataList" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LINK_SEQ" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="LINK_TRT_DTM_VAL" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="LINK_CHG_SC_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DPTCD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="P_ID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="UNIQUE_P_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="P_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="EPLY_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ONPST_DPTCD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="PESN_WK_OGZCD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SARY_WK_OGZCD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DPRCD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="TEND_DEPT_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DEPT_GNTRM_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DEPT_ABBR_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DEPT_BLDMT_NO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PBLAO_SC_CD" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="JSRS_CD" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="JSRS_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DETAI_JSRS_CD" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="JBLN_CD" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="JBLN_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DCTR_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CLS_CD" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="CLS_SEQ" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="COP_CD" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="COP_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="COP_SEQ" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="JOBPS_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="JOBPS_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="JOBPS_LVL_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SRCLS_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PRBTN_YN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PRBTN_REMV_PARNG_YMD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PBLAO_FST_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="FST_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="PS_MINST_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="PS_INST_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PS_COP_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="PS_CLS_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="PS_DEPT_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="PS_JOBPS_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="JOBPS_PRMOT_YMD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RSDOF_EMPLM_YN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CTSV_PRMOT_YN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TTMNT_PBLAO_YN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MNDT_PRCAF_STAFF_YN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RTM_YMD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HLDOF_STAT_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HLDOF_STAT_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PSG_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="URNTH_CLS_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="CTSV_COP_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CTSV_COP_MDFC_YN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CTSV_NTST" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CLS_LVL_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SPWY_TOFOR_SC_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="STDIL_VAL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ONPST_OGZCD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SRVIC_DPRCD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PS_GRFC_MVIN_YMD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CHRGE_BUSN_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LAST_ONPST_INST_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="EMPMN_SC_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TTMNT_COP_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RTM_SC_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="FLDWK_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DSTCT_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MDFC_DTM" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="JSBFR_DEPT_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="rowCount" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataList",
    "rowCount"
})
@XmlRootElement(name = "body")
public class Body {

    protected List<Body.DataList> dataList;
    protected byte rowCount;

    /**
     * Gets the value of the dataList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Body.DataList }
     * 
     * 
     */
    public List<Body.DataList> getDataList() {
        if (dataList == null) {
            dataList = new ArrayList<Body.DataList>();
        }
        return this.dataList;
    }

    /**
     * Gets the value of the rowCount property.
     * 
     */
    public byte getRowCount() {
        return rowCount;
    }

    /**
     * Sets the value of the rowCount property.
     * 
     */
    public void setRowCount(byte value) {
        this.rowCount = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LINK_SEQ" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="LINK_TRT_DTM_VAL" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="LINK_CHG_SC_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DPTCD" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="P_ID" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="UNIQUE_P_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="P_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="EPLY_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ONPST_DPTCD" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="PESN_WK_OGZCD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SARY_WK_OGZCD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DPRCD" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="TEND_DEPT_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DEPT_GNTRM_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DEPT_ABBR_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DEPT_BLDMT_NO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PBLAO_SC_CD" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="JSRS_CD" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="JSRS_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DETAI_JSRS_CD" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="JBLN_CD" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="JBLN_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DCTR_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CLS_CD" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="CLS_SEQ" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="COP_CD" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="COP_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="COP_SEQ" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="JOBPS_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="JOBPS_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="JOBPS_LVL_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SRCLS_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PRBTN_YN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PRBTN_REMV_PARNG_YMD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PBLAO_FST_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="FST_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="PS_MINST_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="PS_INST_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PS_COP_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="PS_CLS_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="PS_DEPT_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="PS_JOBPS_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="JOBPS_PRMOT_YMD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RSDOF_EMPLM_YN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CTSV_PRMOT_YN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TTMNT_PBLAO_YN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MNDT_PRCAF_STAFF_YN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RTM_YMD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HLDOF_STAT_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HLDOF_STAT_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PSG_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="URNTH_CLS_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="CTSV_COP_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CTSV_COP_MDFC_YN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CTSV_NTST" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CLS_LVL_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SPWY_TOFOR_SC_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="STDIL_VAL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ONPST_OGZCD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SRVIC_DPRCD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PS_GRFC_MVIN_YMD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CHRGE_BUSN_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LAST_ONPST_INST_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="EMPMN_SC_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TTMNT_COP_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RTM_SC_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="FLDWK_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DSTCT_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MDFC_DTM" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="JSBFR_DEPT_EMPLM_YMD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "linkseq",
        "linktrtdtmval",
        "linkchgsccd",
        "dptcd",
        "pid",
        "uniquepid",
        "pname",
        "eplyid",
        "onpstdptcd",
        "pesnwkogzcd",
        "sarywkogzcd",
        "dprcd",
        "tenddeptnm",
        "deptgntrmnm",
        "deptabbrnm",
        "deptbldmtno",
        "pblaosccd",
        "jsrscd",
        "jsrsnm",
        "detaijsrscd",
        "jblncd",
        "jblnnm",
        "dctrcd",
        "clscd",
        "clsseq",
        "copcd",
        "copnm",
        "copseq",
        "jobpscd",
        "jobpsnm",
        "jobpslvlcd",
        "srclscd",
        "prbtnyn",
        "prbtnremvparngymd",
        "pblaofstemplmymd",
        "fstemplmymd",
        "psminstemplmymd",
        "psinstemplmymd",
        "pscopemplmymd",
        "psclsemplmymd",
        "psdeptemplmymd",
        "psjobpsemplmymd",
        "jobpsprmotymd",
        "rsdofemplmyn",
        "ctsvprmotyn",
        "ttmntpblaoyn",
        "mndtprcafstaffyn",
        "rtmymd",
        "hldofstatcd",
        "hldofstatnm",
        "psgcd",
        "urnthclsemplmymd",
        "ctsvcopcd",
        "ctsvcopmdfcyn",
        "ctsvntst",
        "clslvlcd",
        "spwytoforsccd",
        "stdilval",
        "onpstogzcd",
        "srvicdprcd",
        "psgrfcmvinymd",
        "chrgebusncd",
        "lastonpstinstemplmymd",
        "empmnscnm",
        "ttmntcopcd",
        "rtmsccd",
        "fldwkcd",
        "dstctcd",
        "mdfcdtm",
        "jsbfrdeptemplmymd"
    })
    public static class DataList {

        @XmlElement(name = "LINK_SEQ")
        protected int linkseq;
        @XmlElement(name = "LINK_TRT_DTM_VAL")
        protected long linktrtdtmval;
        @XmlElement(name = "LINK_CHG_SC_CD", required = true)
        protected String linkchgsccd;
        @XmlElement(name = "DPTCD")
        protected int dptcd;
        @XmlElement(name = "P_ID")
        protected long pid;
        @XmlElement(name = "UNIQUE_P_ID", required = true)
        protected String uniquepid;
        @XmlElement(name = "P_NAME", required = true)
        protected String pname;
        @XmlElement(name = "EPLY_ID", required = true)
        protected String eplyid;
        @XmlElement(name = "ONPST_DPTCD")
        protected int onpstdptcd;
        @XmlElement(name = "PESN_WK_OGZCD", required = true)
        protected String pesnwkogzcd;
        @XmlElement(name = "SARY_WK_OGZCD", required = true)
        protected String sarywkogzcd;
        @XmlElement(name = "DPRCD")
        protected int dprcd;
        @XmlElement(name = "TEND_DEPT_NM", required = true)
        protected String tenddeptnm;
        @XmlElement(name = "DEPT_GNTRM_NM", required = true)
        protected String deptgntrmnm;
        @XmlElement(name = "DEPT_ABBR_NM", required = true)
        protected String deptabbrnm;
        @XmlElement(name = "DEPT_BLDMT_NO", required = true)
        protected String deptbldmtno;
        @XmlElement(name = "PBLAO_SC_CD")
        protected byte pblaosccd;
        @XmlElement(name = "JSRS_CD")
        protected byte jsrscd;
        @XmlElement(name = "JSRS_NM", required = true)
        protected String jsrsnm;
        @XmlElement(name = "DETAI_JSRS_CD")
        protected byte detaijsrscd;
        @XmlElement(name = "JBLN_CD")
        protected byte jblncd;
        @XmlElement(name = "JBLN_NM", required = true)
        protected String jblnnm;
        @XmlElement(name = "DCTR_CD", required = true)
        protected String dctrcd;
        @XmlElement(name = "CLS_CD")
        protected byte clscd;
        @XmlElement(name = "CLS_SEQ")
        protected byte clsseq;
        @XmlElement(name = "COP_CD")
        protected short copcd;
        @XmlElement(name = "COP_NM", required = true)
        protected String copnm;
        @XmlElement(name = "COP_SEQ", required = true)
        protected String copseq;
        @XmlElement(name = "JOBPS_CD", required = true)
        protected String jobpscd;
        @XmlElement(name = "JOBPS_NM", required = true)
        protected String jobpsnm;
        @XmlElement(name = "JOBPS_LVL_CD", required = true)
        protected String jobpslvlcd;
        @XmlElement(name = "SRCLS_CD", required = true)
        protected String srclscd;
        @XmlElement(name = "PRBTN_YN", required = true)
        protected String prbtnyn;
        @XmlElement(name = "PRBTN_REMV_PARNG_YMD", required = true)
        protected String prbtnremvparngymd;
        @XmlElement(name = "PBLAO_FST_EMPLM_YMD")
        protected int pblaofstemplmymd;
        @XmlElement(name = "FST_EMPLM_YMD")
        protected int fstemplmymd;
        @XmlElement(name = "PS_MINST_EMPLM_YMD")
        protected int psminstemplmymd;
        @XmlElement(name = "PS_INST_EMPLM_YMD", required = true)
        protected String psinstemplmymd;
        @XmlElement(name = "PS_COP_EMPLM_YMD")
        protected int pscopemplmymd;
        @XmlElement(name = "PS_CLS_EMPLM_YMD")
        protected int psclsemplmymd;
        @XmlElement(name = "PS_DEPT_EMPLM_YMD")
        protected int psdeptemplmymd;
        @XmlElement(name = "PS_JOBPS_EMPLM_YMD", required = true)
        protected String psjobpsemplmymd;
        @XmlElement(name = "JOBPS_PRMOT_YMD", required = true)
        protected String jobpsprmotymd;
        @XmlElement(name = "RSDOF_EMPLM_YN", required = true)
        protected String rsdofemplmyn;
        @XmlElement(name = "CTSV_PRMOT_YN", required = true)
        protected String ctsvprmotyn;
        @XmlElement(name = "TTMNT_PBLAO_YN", required = true)
        protected String ttmntpblaoyn;
        @XmlElement(name = "MNDT_PRCAF_STAFF_YN", required = true)
        protected String mndtprcafstaffyn;
        @XmlElement(name = "RTM_YMD", required = true)
        protected String rtmymd;
        @XmlElement(name = "HLDOF_STAT_CD", required = true)
        protected String hldofstatcd;
        @XmlElement(name = "HLDOF_STAT_NM", required = true)
        protected String hldofstatnm;
        @XmlElement(name = "PSG_CD", required = true)
        protected String psgcd;
        @XmlElement(name = "URNTH_CLS_EMPLM_YMD")
        protected int urnthclsemplmymd;
        @XmlElement(name = "CTSV_COP_CD", required = true)
        protected String ctsvcopcd;
        @XmlElement(name = "CTSV_COP_MDFC_YN", required = true)
        protected String ctsvcopmdfcyn;
        @XmlElement(name = "CTSV_NTST", required = true)
        protected String ctsvntst;
        @XmlElement(name = "CLS_LVL_CD", required = true)
        protected String clslvlcd;
        @XmlElement(name = "SPWY_TOFOR_SC_CD", required = true)
        protected String spwytoforsccd;
        @XmlElement(name = "STDIL_VAL", required = true)
        protected String stdilval;
        @XmlElement(name = "ONPST_OGZCD", required = true)
        protected String onpstogzcd;
        @XmlElement(name = "SRVIC_DPRCD", required = true)
        protected String srvicdprcd;
        @XmlElement(name = "PS_GRFC_MVIN_YMD", required = true)
        protected String psgrfcmvinymd;
        @XmlElement(name = "CHRGE_BUSN_CD", required = true)
        protected String chrgebusncd;
        @XmlElement(name = "LAST_ONPST_INST_EMPLM_YMD")
        protected int lastonpstinstemplmymd;
        @XmlElement(name = "EMPMN_SC_NM", required = true)
        protected String empmnscnm;
        @XmlElement(name = "TTMNT_COP_CD", required = true)
        protected String ttmntcopcd;
        @XmlElement(name = "RTM_SC_CD", required = true)
        protected String rtmsccd;
        @XmlElement(name = "FLDWK_CD", required = true)
        protected String fldwkcd;
        @XmlElement(name = "DSTCT_CD", required = true)
        protected String dstctcd;
        @XmlElement(name = "MDFC_DTM")
        protected long mdfcdtm;
        @XmlElement(name = "JSBFR_DEPT_EMPLM_YMD", required = true)
        protected String jsbfrdeptemplmymd;

        /**
         * Gets the value of the linkseq property.
         * 
         */
        public int getLINKSEQ() {
            return linkseq;
        }

        /**
         * Sets the value of the linkseq property.
         * 
         */
        public void setLINKSEQ(int value) {
            this.linkseq = value;
        }

        /**
         * Gets the value of the linktrtdtmval property.
         * 
         */
        public long getLINKTRTDTMVAL() {
            return linktrtdtmval;
        }

        /**
         * Sets the value of the linktrtdtmval property.
         * 
         */
        public void setLINKTRTDTMVAL(long value) {
            this.linktrtdtmval = value;
        }

        /**
         * Gets the value of the linkchgsccd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLINKCHGSCCD() {
            return linkchgsccd;
        }

        /**
         * Sets the value of the linkchgsccd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLINKCHGSCCD(String value) {
            this.linkchgsccd = value;
        }

        /**
         * Gets the value of the dptcd property.
         * 
         */
        public int getDPTCD() {
            return dptcd;
        }

        /**
         * Sets the value of the dptcd property.
         * 
         */
        public void setDPTCD(int value) {
            this.dptcd = value;
        }

        /**
         * Gets the value of the pid property.
         * 
         */
        public long getPID() {
            return pid;
        }

        /**
         * Sets the value of the pid property.
         * 
         */
        public void setPID(long value) {
            this.pid = value;
        }

        /**
         * Gets the value of the uniquepid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUNIQUEPID() {
            return uniquepid;
        }

        /**
         * Sets the value of the uniquepid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUNIQUEPID(String value) {
            this.uniquepid = value;
        }

        /**
         * Gets the value of the pname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPNAME() {
            return pname;
        }

        /**
         * Sets the value of the pname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPNAME(String value) {
            this.pname = value;
        }

        /**
         * Gets the value of the eplyid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEPLYID() {
            return eplyid;
        }

        /**
         * Sets the value of the eplyid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEPLYID(String value) {
            this.eplyid = value;
        }

        /**
         * Gets the value of the onpstdptcd property.
         * 
         */
        public int getONPSTDPTCD() {
            return onpstdptcd;
        }

        /**
         * Sets the value of the onpstdptcd property.
         * 
         */
        public void setONPSTDPTCD(int value) {
            this.onpstdptcd = value;
        }

        /**
         * Gets the value of the pesnwkogzcd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPESNWKOGZCD() {
            return pesnwkogzcd;
        }

        /**
         * Sets the value of the pesnwkogzcd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPESNWKOGZCD(String value) {
            this.pesnwkogzcd = value;
        }

        /**
         * Gets the value of the sarywkogzcd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSARYWKOGZCD() {
            return sarywkogzcd;
        }

        /**
         * Sets the value of the sarywkogzcd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSARYWKOGZCD(String value) {
            this.sarywkogzcd = value;
        }

        /**
         * Gets the value of the dprcd property.
         * 
         */
        public int getDPRCD() {
            return dprcd;
        }

        /**
         * Sets the value of the dprcd property.
         * 
         */
        public void setDPRCD(int value) {
            this.dprcd = value;
        }

        /**
         * Gets the value of the tenddeptnm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTENDDEPTNM() {
            return tenddeptnm;
        }

        /**
         * Sets the value of the tenddeptnm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTENDDEPTNM(String value) {
            this.tenddeptnm = value;
        }

        /**
         * Gets the value of the deptgntrmnm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDEPTGNTRMNM() {
            return deptgntrmnm;
        }

        /**
         * Sets the value of the deptgntrmnm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDEPTGNTRMNM(String value) {
            this.deptgntrmnm = value;
        }

        /**
         * Gets the value of the deptabbrnm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDEPTABBRNM() {
            return deptabbrnm;
        }

        /**
         * Sets the value of the deptabbrnm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDEPTABBRNM(String value) {
            this.deptabbrnm = value;
        }

        /**
         * Gets the value of the deptbldmtno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDEPTBLDMTNO() {
            return deptbldmtno;
        }

        /**
         * Sets the value of the deptbldmtno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDEPTBLDMTNO(String value) {
            this.deptbldmtno = value;
        }

        /**
         * Gets the value of the pblaosccd property.
         * 
         */
        public byte getPBLAOSCCD() {
            return pblaosccd;
        }

        /**
         * Sets the value of the pblaosccd property.
         * 
         */
        public void setPBLAOSCCD(byte value) {
            this.pblaosccd = value;
        }

        /**
         * Gets the value of the jsrscd property.
         * 
         */
        public byte getJSRSCD() {
            return jsrscd;
        }

        /**
         * Sets the value of the jsrscd property.
         * 
         */
        public void setJSRSCD(byte value) {
            this.jsrscd = value;
        }

        /**
         * Gets the value of the jsrsnm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJSRSNM() {
            return jsrsnm;
        }

        /**
         * Sets the value of the jsrsnm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJSRSNM(String value) {
            this.jsrsnm = value;
        }

        /**
         * Gets the value of the detaijsrscd property.
         * 
         */
        public byte getDETAIJSRSCD() {
            return detaijsrscd;
        }

        /**
         * Sets the value of the detaijsrscd property.
         * 
         */
        public void setDETAIJSRSCD(byte value) {
            this.detaijsrscd = value;
        }

        /**
         * Gets the value of the jblncd property.
         * 
         */
        public byte getJBLNCD() {
            return jblncd;
        }

        /**
         * Sets the value of the jblncd property.
         * 
         */
        public void setJBLNCD(byte value) {
            this.jblncd = value;
        }

        /**
         * Gets the value of the jblnnm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJBLNNM() {
            return jblnnm;
        }

        /**
         * Sets the value of the jblnnm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJBLNNM(String value) {
            this.jblnnm = value;
        }

        /**
         * Gets the value of the dctrcd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDCTRCD() {
            return dctrcd;
        }

        /**
         * Sets the value of the dctrcd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDCTRCD(String value) {
            this.dctrcd = value;
        }

        /**
         * Gets the value of the clscd property.
         * 
         */
        public byte getCLSCD() {
            return clscd;
        }

        /**
         * Sets the value of the clscd property.
         * 
         */
        public void setCLSCD(byte value) {
            this.clscd = value;
        }

        /**
         * Gets the value of the clsseq property.
         * 
         */
        public byte getCLSSEQ() {
            return clsseq;
        }

        /**
         * Sets the value of the clsseq property.
         * 
         */
        public void setCLSSEQ(byte value) {
            this.clsseq = value;
        }

        /**
         * Gets the value of the copcd property.
         * 
         */
        public short getCOPCD() {
            return copcd;
        }

        /**
         * Sets the value of the copcd property.
         * 
         */
        public void setCOPCD(short value) {
            this.copcd = value;
        }

        /**
         * Gets the value of the copnm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCOPNM() {
            return copnm;
        }

        /**
         * Sets the value of the copnm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCOPNM(String value) {
            this.copnm = value;
        }

        /**
         * Gets the value of the copseq property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCOPSEQ() {
            return copseq;
        }

        /**
         * Sets the value of the copseq property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCOPSEQ(String value) {
            this.copseq = value;
        }

        /**
         * Gets the value of the jobpscd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJOBPSCD() {
            return jobpscd;
        }

        /**
         * Sets the value of the jobpscd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJOBPSCD(String value) {
            this.jobpscd = value;
        }

        /**
         * Gets the value of the jobpsnm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJOBPSNM() {
            return jobpsnm;
        }

        /**
         * Sets the value of the jobpsnm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJOBPSNM(String value) {
            this.jobpsnm = value;
        }

        /**
         * Gets the value of the jobpslvlcd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJOBPSLVLCD() {
            return jobpslvlcd;
        }

        /**
         * Sets the value of the jobpslvlcd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJOBPSLVLCD(String value) {
            this.jobpslvlcd = value;
        }

        /**
         * Gets the value of the srclscd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSRCLSCD() {
            return srclscd;
        }

        /**
         * Sets the value of the srclscd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSRCLSCD(String value) {
            this.srclscd = value;
        }

        /**
         * Gets the value of the prbtnyn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPRBTNYN() {
            return prbtnyn;
        }

        /**
         * Sets the value of the prbtnyn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPRBTNYN(String value) {
            this.prbtnyn = value;
        }

        /**
         * Gets the value of the prbtnremvparngymd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPRBTNREMVPARNGYMD() {
            return prbtnremvparngymd;
        }

        /**
         * Sets the value of the prbtnremvparngymd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPRBTNREMVPARNGYMD(String value) {
            this.prbtnremvparngymd = value;
        }

        /**
         * Gets the value of the pblaofstemplmymd property.
         * 
         */
        public int getPBLAOFSTEMPLMYMD() {
            return pblaofstemplmymd;
        }

        /**
         * Sets the value of the pblaofstemplmymd property.
         * 
         */
        public void setPBLAOFSTEMPLMYMD(int value) {
            this.pblaofstemplmymd = value;
        }

        /**
         * Gets the value of the fstemplmymd property.
         * 
         */
        public int getFSTEMPLMYMD() {
            return fstemplmymd;
        }

        /**
         * Sets the value of the fstemplmymd property.
         * 
         */
        public void setFSTEMPLMYMD(int value) {
            this.fstemplmymd = value;
        }

        /**
         * Gets the value of the psminstemplmymd property.
         * 
         */
        public int getPSMINSTEMPLMYMD() {
            return psminstemplmymd;
        }

        /**
         * Sets the value of the psminstemplmymd property.
         * 
         */
        public void setPSMINSTEMPLMYMD(int value) {
            this.psminstemplmymd = value;
        }

        /**
         * Gets the value of the psinstemplmymd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPSINSTEMPLMYMD() {
            return psinstemplmymd;
        }

        /**
         * Sets the value of the psinstemplmymd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPSINSTEMPLMYMD(String value) {
            this.psinstemplmymd = value;
        }

        /**
         * Gets the value of the pscopemplmymd property.
         * 
         */
        public int getPSCOPEMPLMYMD() {
            return pscopemplmymd;
        }

        /**
         * Sets the value of the pscopemplmymd property.
         * 
         */
        public void setPSCOPEMPLMYMD(int value) {
            this.pscopemplmymd = value;
        }

        /**
         * Gets the value of the psclsemplmymd property.
         * 
         */
        public int getPSCLSEMPLMYMD() {
            return psclsemplmymd;
        }

        /**
         * Sets the value of the psclsemplmymd property.
         * 
         */
        public void setPSCLSEMPLMYMD(int value) {
            this.psclsemplmymd = value;
        }

        /**
         * Gets the value of the psdeptemplmymd property.
         * 
         */
        public int getPSDEPTEMPLMYMD() {
            return psdeptemplmymd;
        }

        /**
         * Sets the value of the psdeptemplmymd property.
         * 
         */
        public void setPSDEPTEMPLMYMD(int value) {
            this.psdeptemplmymd = value;
        }

        /**
         * Gets the value of the psjobpsemplmymd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPSJOBPSEMPLMYMD() {
            return psjobpsemplmymd;
        }

        /**
         * Sets the value of the psjobpsemplmymd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPSJOBPSEMPLMYMD(String value) {
            this.psjobpsemplmymd = value;
        }

        /**
         * Gets the value of the jobpsprmotymd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJOBPSPRMOTYMD() {
            return jobpsprmotymd;
        }

        /**
         * Sets the value of the jobpsprmotymd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJOBPSPRMOTYMD(String value) {
            this.jobpsprmotymd = value;
        }

        /**
         * Gets the value of the rsdofemplmyn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRSDOFEMPLMYN() {
            return rsdofemplmyn;
        }

        /**
         * Sets the value of the rsdofemplmyn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRSDOFEMPLMYN(String value) {
            this.rsdofemplmyn = value;
        }

        /**
         * Gets the value of the ctsvprmotyn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCTSVPRMOTYN() {
            return ctsvprmotyn;
        }

        /**
         * Sets the value of the ctsvprmotyn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCTSVPRMOTYN(String value) {
            this.ctsvprmotyn = value;
        }

        /**
         * Gets the value of the ttmntpblaoyn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTTMNTPBLAOYN() {
            return ttmntpblaoyn;
        }

        /**
         * Sets the value of the ttmntpblaoyn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTTMNTPBLAOYN(String value) {
            this.ttmntpblaoyn = value;
        }

        /**
         * Gets the value of the mndtprcafstaffyn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMNDTPRCAFSTAFFYN() {
            return mndtprcafstaffyn;
        }

        /**
         * Sets the value of the mndtprcafstaffyn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMNDTPRCAFSTAFFYN(String value) {
            this.mndtprcafstaffyn = value;
        }

        /**
         * Gets the value of the rtmymd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRTMYMD() {
            return rtmymd;
        }

        /**
         * Sets the value of the rtmymd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRTMYMD(String value) {
            this.rtmymd = value;
        }

        /**
         * Gets the value of the hldofstatcd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHLDOFSTATCD() {
            return hldofstatcd;
        }

        /**
         * Sets the value of the hldofstatcd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHLDOFSTATCD(String value) {
            this.hldofstatcd = value;
        }

        /**
         * Gets the value of the hldofstatnm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHLDOFSTATNM() {
            return hldofstatnm;
        }

        /**
         * Sets the value of the hldofstatnm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHLDOFSTATNM(String value) {
            this.hldofstatnm = value;
        }

        /**
         * Gets the value of the psgcd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPSGCD() {
            return psgcd;
        }

        /**
         * Sets the value of the psgcd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPSGCD(String value) {
            this.psgcd = value;
        }

        /**
         * Gets the value of the urnthclsemplmymd property.
         * 
         */
        public int getURNTHCLSEMPLMYMD() {
            return urnthclsemplmymd;
        }

        /**
         * Sets the value of the urnthclsemplmymd property.
         * 
         */
        public void setURNTHCLSEMPLMYMD(int value) {
            this.urnthclsemplmymd = value;
        }

        /**
         * Gets the value of the ctsvcopcd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCTSVCOPCD() {
            return ctsvcopcd;
        }

        /**
         * Sets the value of the ctsvcopcd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCTSVCOPCD(String value) {
            this.ctsvcopcd = value;
        }

        /**
         * Gets the value of the ctsvcopmdfcyn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCTSVCOPMDFCYN() {
            return ctsvcopmdfcyn;
        }

        /**
         * Sets the value of the ctsvcopmdfcyn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCTSVCOPMDFCYN(String value) {
            this.ctsvcopmdfcyn = value;
        }

        /**
         * Gets the value of the ctsvntst property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCTSVNTST() {
            return ctsvntst;
        }

        /**
         * Sets the value of the ctsvntst property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCTSVNTST(String value) {
            this.ctsvntst = value;
        }

        /**
         * Gets the value of the clslvlcd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCLSLVLCD() {
            return clslvlcd;
        }

        /**
         * Sets the value of the clslvlcd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCLSLVLCD(String value) {
            this.clslvlcd = value;
        }

        /**
         * Gets the value of the spwytoforsccd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSPWYTOFORSCCD() {
            return spwytoforsccd;
        }

        /**
         * Sets the value of the spwytoforsccd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSPWYTOFORSCCD(String value) {
            this.spwytoforsccd = value;
        }

        /**
         * Gets the value of the stdilval property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSTDILVAL() {
            return stdilval;
        }

        /**
         * Sets the value of the stdilval property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSTDILVAL(String value) {
            this.stdilval = value;
        }

        /**
         * Gets the value of the onpstogzcd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getONPSTOGZCD() {
            return onpstogzcd;
        }

        /**
         * Sets the value of the onpstogzcd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setONPSTOGZCD(String value) {
            this.onpstogzcd = value;
        }

        /**
         * Gets the value of the srvicdprcd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSRVICDPRCD() {
            return srvicdprcd;
        }

        /**
         * Sets the value of the srvicdprcd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSRVICDPRCD(String value) {
            this.srvicdprcd = value;
        }

        /**
         * Gets the value of the psgrfcmvinymd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPSGRFCMVINYMD() {
            return psgrfcmvinymd;
        }

        /**
         * Sets the value of the psgrfcmvinymd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPSGRFCMVINYMD(String value) {
            this.psgrfcmvinymd = value;
        }

        /**
         * Gets the value of the chrgebusncd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCHRGEBUSNCD() {
            return chrgebusncd;
        }

        /**
         * Sets the value of the chrgebusncd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCHRGEBUSNCD(String value) {
            this.chrgebusncd = value;
        }

        /**
         * Gets the value of the lastonpstinstemplmymd property.
         * 
         */
        public int getLASTONPSTINSTEMPLMYMD() {
            return lastonpstinstemplmymd;
        }

        /**
         * Sets the value of the lastonpstinstemplmymd property.
         * 
         */
        public void setLASTONPSTINSTEMPLMYMD(int value) {
            this.lastonpstinstemplmymd = value;
        }

        /**
         * Gets the value of the empmnscnm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEMPMNSCNM() {
            return empmnscnm;
        }

        /**
         * Sets the value of the empmnscnm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEMPMNSCNM(String value) {
            this.empmnscnm = value;
        }

        /**
         * Gets the value of the ttmntcopcd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTTMNTCOPCD() {
            return ttmntcopcd;
        }

        /**
         * Sets the value of the ttmntcopcd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTTMNTCOPCD(String value) {
            this.ttmntcopcd = value;
        }

        /**
         * Gets the value of the rtmsccd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRTMSCCD() {
            return rtmsccd;
        }

        /**
         * Sets the value of the rtmsccd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRTMSCCD(String value) {
            this.rtmsccd = value;
        }

        /**
         * Gets the value of the fldwkcd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFLDWKCD() {
            return fldwkcd;
        }

        /**
         * Sets the value of the fldwkcd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFLDWKCD(String value) {
            this.fldwkcd = value;
        }

        /**
         * Gets the value of the dstctcd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDSTCTCD() {
            return dstctcd;
        }

        /**
         * Sets the value of the dstctcd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDSTCTCD(String value) {
            this.dstctcd = value;
        }

        /**
         * Gets the value of the mdfcdtm property.
         * 
         */
        public long getMDFCDTM() {
            return mdfcdtm;
        }

        /**
         * Sets the value of the mdfcdtm property.
         * 
         */
        public void setMDFCDTM(long value) {
            this.mdfcdtm = value;
        }

        /**
         * Gets the value of the jsbfrdeptemplmymd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJSBFRDEPTEMPLMYMD() {
            return jsbfrdeptemplmymd;
        }

        /**
         * Sets the value of the jsbfrdeptemplmymd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJSBFRDEPTEMPLMYMD(String value) {
            this.jsbfrdeptemplmymd = value;
        }

    }

}
